using AutomationPractice;
using NUnit.Allure.Core;
using NUnit.Framework;
using OpenQA.Selenium;

namespace TestAutomationPractice;

[AllureNUnit]
[TestFixture]
public class Tests
{
    private const string URL = "http://automationpractice.com/index.php?controller=authentication&back=my-account";
    private const string MY_WISHLIST_NAME = "DreamPurchases";

    [OneTimeSetUp]
    public void Setup()
    {
        BrowserEnvironment.SetEnvironment("local", "chrome");
    }

    [Test]
    public void TestCreateAcount()
    {
        try
        {
            BrowserEnvironment.LoadApplication(URL);
            var signupPage = Page.Login.SubmitEmailForm(DataFromFile.GetElementValue("email"));
            Assert.IsTrue(signupPage.IsLoaded(), "SignUp page was not loaded");
        }
        catch (Exception e)
        {
            Assert.Fail(e.Message);
        }
    }


    [Test]
    [TestCaseSource(typeof(DataFromFile), nameof(DataFromFile.RegisterFormData))]
    public void TestSignUp(string firstName, string lastName, string email, string password,
        string address, string city, string state, string zipCode, string country, string mobile_phone, string alias)
    {
        try
        {
            BrowserEnvironment.LoadApplication(URL);
            var signupPage = Page.Login.SubmitEmailForm(DataFromFile.GetElementValue("email"));
            Assert.IsTrue(signupPage.IsLoaded(), "SignUp page was not loaded");
            var userHomePage = signupPage.FillRegistrationForm(firstName, lastName, email, password,
        address, city, state, zipCode, country, mobile_phone, alias);
            Assert.IsTrue(userHomePage.IsPageLoaded(), "User homepage was not loaded");
        }
        catch (Exception e)
        {
            Assert.Fail(e.Message);
        }
    }

    [Test]
    public void TestLogIn()
    {
        try
        {
            BrowserEnvironment.LoadApplication(URL);
            var logInPage = Page.Login;
            var userHomePage = logInPage.FillLogInDetails(DataFromFile.GetElementValue("email"), DataFromFile.GetElementValue("password"));
            Assert.IsTrue(userHomePage.IsPageLoaded(), "User homepage was not loaded");
        }
        catch (Exception e)
        {
            Assert.Fail(e.Message);
        }
    }

    [Test]
    public void TestWishList()
    {
        try
        {
            BrowserEnvironment.LoadApplication(URL);
            var logInPage = Page.Login;
            var userHomePage = logInPage.FillLogInDetails(DataFromFile.GetElementValue("email"), DataFromFile.GetElementValue("password"));
            Assert.IsTrue(userHomePage.IsPageLoaded(), "User homepage was not loaded");
            var wishlists = userHomePage.ClickWishlist();
            Assert.IsTrue(wishlists.IsPageLoaded(), "wishlists page was not loaded");
        }
        catch (Exception e)
        {
            Assert.Fail(e.Message);
        }
    }

    [Test]
    public void TestAddToWishList()
    {
        try
        {
            BrowserEnvironment.LoadApplication(URL);
            var logInPage = Page.Login;
            var userHomePage = logInPage.FillLogInDetails(DataFromFile.GetElementValue("email"), DataFromFile.GetElementValue("password"));
            Assert.IsTrue(userHomePage.IsPageLoaded(), "User homepage was not loaded");
            var wishlists = userHomePage.ClickWishlist();
            Assert.IsTrue(wishlists.IsPageLoaded(), "Wishlists page was not loaded");
            Assert.IsFalse(wishlists.DoesAutoGeneratedWishListExist(), "There is no auto generated wishlist");
            var productPage = wishlists.ClickProduct();
            Assert.IsTrue(productPage.IsPageLoaded(), "Product page was not loaded");
            productPage = productPage.AddToWishList();
            wishlists = productPage.GoToUserHomePage().ClickWishlist();
            Assert.IsTrue(wishlists.CheckProductAddedToAutoWishList(), "Product was not added to the wishlist");
        }
        catch (Exception e)
        {
            Assert.Fail(e.Message);
        }
    }

    [Test]
    public void TestAddToCustomWishList()
    {
        try
        {
            BrowserEnvironment.LoadApplication(URL);
            var logInPage = Page.Login;
            var userHomePage = logInPage.FillLogInDetails(DataFromFile.GetElementValue("email"), DataFromFile.GetElementValue("password"));
            Assert.IsTrue(userHomePage.IsPageLoaded(), "User homepage was not loaded");
            var wishlists = userHomePage.ClickWishlist();
            Assert.IsTrue(wishlists.IsPageLoaded(), "Wishlists page was not loaded");
            wishlists = wishlists.CreateMyWishList(MY_WISHLIST_NAME);
            Assert.IsTrue( wishlists.DoesCustomWishlistWasCreated(MY_WISHLIST_NAME), $"Wishlist with name {MY_WISHLIST_NAME} was not created");
            var productPage = wishlists.ClickProduct();
            Assert.IsTrue(productPage.IsPageLoaded(), "Product page was not loaded");
            productPage = productPage.AddToWishList();
            wishlists = productPage.GoToUserHomePage().ClickWishlist();
            Assert.IsTrue(wishlists.CheckProductAddedToCustomWishList(MY_WISHLIST_NAME), "Product was not added to the wishlist");
        }
        catch (Exception e)
        {
            Assert.Fail(e.Message);
        }
    }

    [Test]
    public void TestAbilityToAddToCart()
    {
        try
        {
            BrowserEnvironment.LoadApplication(URL);
            var logInPage = Page.Login;
            var userHomePage = logInPage.FillLogInDetails(DataFromFile.GetElementValue("email"), DataFromFile.GetElementValue("password"));
            Assert.IsTrue(userHomePage.IsPageLoaded(), "User homepage was not loaded");
            var dressesPage = userHomePage.ClickDresses();
            Assert.IsTrue(dressesPage.IsPageLoaded(), "Dresses page was not loaded");
            dressesPage = dressesPage.AddThreeDressesToTheCart();
            var cartPage = dressesPage.GoToCart();
            Assert.IsTrue(cartPage.IsPageLoaded(), "Cart page was not loaded");
            var expectedCartTotal = 107.97;
            Assert.AreEqual(expectedCartTotal, cartPage.GetCartTotal(), "Cart total doesn't match");
        }
        catch (Exception e)
        {
            Assert.Fail(e.Message);
        }
    }

    [OneTimeTearDown]
    public void CleanUp()
    {
        BrowserEnvironment.CloseDriver();
    }
}
