namespace TestAutomationPractice;

[TestFixture]
[AllureNUnit]
public class WishlistTest : TestBaseClass
{
    [Test, Order(1)]
    public void TestUserLogIn()
    {
        try
        {
            var logInPage = Page.Login.LoadPage();
            var userHomePage = logInPage.FillLogInDetails(DataFromFile.GetElementValue("email"), DataFromFile.GetElementValue("password"));
            Assert.IsTrue(userHomePage.IsPageLoaded(), "User homepage was not loaded");
        }
        catch (Exception e)
        {
            Assert.Fail(e.Message);
        }
    }

    [Test, Order(2)]
    public void TestWishlistPageLoaded()
    {
        try
        {
            var wishlists = Page.UserHome.ClickWishlist();
            Assert.IsTrue(wishlists.IsPageLoaded(), "wishlists page was not loaded");
        }
        catch (Exception e)
        {
            Assert.Fail(e.Message);
        }
    }

    [Test, Order(3)]
    public void TestExistanceOfAutoGeneratedWishlist()
    {
        try
        {
            var wishlists = Page.UserHome.ClickWishlist();
            Assert.IsFalse(wishlists.DoesAutoGeneratedWishListExist(), "There is no auto generated wishlist");
        }
        catch (Exception e)
        {
            Assert.Fail(e.Message);
        }
    }

    [Test, Order(4)]
    public void TestProductPageLoaded()
    {
        try
        {
            var productPage = Page.WishLists.ClickProduct();
            Assert.IsTrue(productPage.IsPageLoaded(), "Product page was not loaded");
        }
        catch (Exception e)
        {
            Assert.Fail(e.Message);
        }
    }

    [Test, Order(5)]
    public void TestAddToWishList()
    {
        try
        {
            var productPage = Page.ProductPage.AddToWishList();
            var wishlists = productPage.GoToUserHomePage().ClickWishlist();
            Assert.IsTrue(wishlists.CheckProductAddedToAutoWishList(), "Product was not added to the wishlist");
        }
        catch (Exception e)
        {
            Assert.Fail(e.Message);
        }
    }
}
